apiVersion: v1
kind: ServiceAccount
metadata:
  name: opnsense-lb-controller
  namespace: opnsense-lb-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opnsense-lb-controller
rules:
  - apiGroups: [""]
    resources: ["services", "endpoints", "nodes"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["services/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: opnsense-lb-controller
  namespace: opnsense-lb-controller
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: opnsense-lb-controller
  namespace: opnsense-lb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: opnsense-lb-controller
subjects:
  - kind: ServiceAccount
    name: opnsense-lb-controller
    namespace: opnsense-lb-controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opnsense-lb-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opnsense-lb-controller
subjects:
  - kind: ServiceAccount
    name: opnsense-lb-controller
    namespace: opnsense-lb-controller
