apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "opnsense-lb-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opnsense-lb-controller.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "opnsense-lb-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opnsense-lb-controller.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "opnsense-lb-controller.name" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "opnsense-lb-controller.name" . }}
    namespace: {{ .Release.Namespace }}
