{{- if not .Values.opnsense.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opnsense-lb-controller.name" . }}-api
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opnsense-lb-controller.labels" . | nindent 4 }}
type: Opaque
stringData:
  url: {{ .Values.opnsense.url | quote }}
  apiKey: {{ .Values.opnsense.apiKey | quote }}
  apiSecret: {{ .Values.opnsense.apiSecret | quote }}
{{- end }}
