apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "opnsense-lb-controller.name" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opnsense-lb-controller.labels" . | nindent 4 }}
